---
- name: Configure node2
  hosts: node2
  tasks:
    - name: Configure Hostname
      ansible.builtin.hostname:
        name: node2.example.com

    - name: Configure Host File
      ansible.builtin.blockinfile:
        path: /etc/hosts
        block: |
          192.168.55.201 node1.example.com
          192.168.55.200 repos.example.com


    - name: Set Welcome Message
      ansible.builtin.copy:
        src: ../scripts/welcome.sh
        dest: /etc/profile.d/welcome.sh
        owner: vagrant
        group: vagrant
        mode: '0755'
